### ISSUE TITLE
Add the ablility to Write to CsvDestination 

### ISSUE THREAD

**Issue by waseembashir** [jsnape/deeply#6]

**Comment by jsnape** [comment]
So on one hand I don't want to depend on any other external libraries since users may chose other implementations; on the other there is no point reinventing the wheel when perfectly good libraries exist.

The best compromise seems to be an additional assembly that implements a lot of this extra functionality. Deeply.Extras

**Comment by waseembashir** [comment]
Any reason why CsvBulkRepository doesn't include CsvClassMap<T> as a member?

**Comment by jsnape** [comment]
Yes, you can register a class map with the CsvConfiguration passed to the constructor.

``` C#
    var csvConfiguration = new CsvConfiguration();
    csvConfiguration.RegisterClassMap(myClassMap);
    var target = new CsvBulkRepository<FakeEntity>("afile.csv",  csvConfiguration);
```
